# Student_marks data set

In [3]:
import pandas as pd

df = pd.read_csv(r"C:\Users\ASUS\Pictures\Downloads\student_marks.csv")

df.head()

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
0,John,M,05-04-1988,55,45,56,87,21,52,89,65
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53

In [4]:
df

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
0,John,M,05-04-1988,55,45,56,87,21,52,89,65
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53
5,Annu,F,05-04-1988,45,87,52,89,55,89,87,52
6,pooja,F,04-05-1987,55,64,61,58,75,58,64,61
7,Ritesh,M,25-05-1989,54,76,87,56,25,56,76,87
8,Farha,F,12-08-1990,55,63,89,75,78,75,63,89
9,Mukesh,M,02-09-1989,96,46,77,83,58,83,46,77

#### 1)Probability using zscore:

In [5]:
print(df.columns)
print(df.head())

Index(['Unnamed: 0', 'Gender', 'DOB', 'Maths', 'Physics', 'Chemistry',
       'English', 'Biology', 'Economics', 'History', 'Civics'],
      dtype='str')
  Unnamed: 0 Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0       John      M  05-04-1988     55       45         56       87       21
1     Suresh      M  04-05-1987     75       96         78       64       90
2     Ramesh      M  25-05-1989     25       54         89       76       95
3    Jessica      F  12-08-1990     78       96         86       63       54
4   Jennifer      F  02-09-1989     58       96         78       46       96

   Economics  History  Civics
0         52       89      65
1         61       58       2
2         87       56      74
3         89       75      45
4         77       83      53

#### calculating the probability that the students scpre is less than 60

In [6]:
!pip install scipy

Requirement already satisfied: scipy in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.18.1)
Requirement already satisfied: numpy<2.8,>=2.0.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scipy) (2.5.1)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [9]:
from scipy.stats import norm

mean = df['Maths'].mean()
std = df['Maths'].std()

z = (60 - mean) / std
print("Z-score:", z)

probability = norm.cdf(1)
print("Probability:", probability)

Z-score: 0.02055445508285437
Probability: 0.8413447460685429

In [10]:
from scipy.stats import norm

mean = df['Maths'].mean()
std = df['Maths'].std()

z = (60 - mean) / std
print("Z-score:", z)

probability = norm.cdf(z)
print("Probability:", probability)

Z-score: 0.02055445508285437
Probability: 0.5081994638198334

#### Probability of scoring less than 70 in Physics

In [12]:
from scipy.stats import norm

mean = df['Physics'].mean()
std = df['Physics'].std()

x = 70

z = (x - mean) / std
print("Z-score:", z)

probability = norm.cdf(1)
print("Probability:", probability)

Z-score: -0.11131783689280991
Probability: 0.8413447460685429

In [13]:
from scipy.stats import norm

mean = df['Physics'].mean()
std = df['Physics'].std()

x = 70

z = (x - mean) / std
print("Z-score:", z)

probability = norm.cdf(z)
print("Probability:", probability)

Z-score: -0.11131783689280991
Probability: 0.45568215575810433

#### probability of scoring more than 70.

In [14]:
probability_above_70 = 1 - norm.cdf(z)

print("Probability of scoring above 70:", probability_above_70)

Probability of scoring above 70: 0.5443178442418957

## 2)Outlier Detection:

In [15]:
import numpy as np
from scipy.stats import zscore

z_scores = zscore(df['Maths'])

threshold = 3

outliers = df[np.abs(z_scores) > threshold]

print("Outliers:")
print(outliers[['Unnamed: 0', 'Maths']])

Outliers:
Empty DataFrame
Columns: [Unnamed: 0, Maths]
Index: []

 no outlier for the threshold of 3

In [16]:
threshold=2
outliers = df[np.abs(z_scores) > threshold]

print("Outliers:")
print(outliers[['Unnamed: 0', 'Maths']])

Outliers:
Empty DataFrame
Columns: [Unnamed: 0, Maths]
Index: []

In [17]:
#using IQR
Q1 = df['Maths'].quantile(0.25)
Q3 = df['Maths'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df['Maths'] < lower) |
    (df['Maths'] > upper)
]

print("Lower limit:", lower)
print("Upper limit:", upper)
print("Outliers:")
print(outliers[['Unnamed: 0', 'Maths']])

Lower limit: 29.5
Upper limit: 95.5
Outliers:
  Unnamed: 0  Maths
2     Ramesh     25
9     Mukesh     96

In [23]:
import numpy as np
from scipy.stats import zscore

z_scores = zscore(df['Civics'])

threshold = 3

outliers = df[np.abs(z_scores) > threshold]

print("Outliers:")
print(outliers["Civics"])

Outliers:
Series([], Name: Civics, dtype: int64)

In [19]:
subjects = [
    'Maths', 'Physics', 'Chemistry', 'English',
    'Biology', 'Economics', 'History', 'Civics'
]

for col in subjects:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"\n{col} outliers:")
    print(outliers[['Unnamed: 0', col]])

Maths outliers:
  Unnamed: 0  Maths
2     Ramesh     25
9     Mukesh     96

Physics outliers:
Empty DataFrame
Columns: [Unnamed: 0, Physics]
Index: []

Chemistry outliers:
Empty DataFrame
Columns: [Unnamed: 0, Chemistry]
Index: []

English outliers:
Empty DataFrame
Columns: [Unnamed: 0, English]
Index: []

Biology outliers:
Empty DataFrame
Columns: [Unnamed: 0, Biology]
Index: []

Economics outliers:
Empty DataFrame
Columns: [Unnamed: 0, Economics]
Index: []

History outliers:
Empty DataFrame
Columns: [Unnamed: 0, History]
Index: []

Civics outliers:
  Unnamed: 0  Civics
1     Suresh       2

In [27]:
from sklearn.preprocessing import StandardScaler

data = df[subjects]
scaler = StandardScaler()
scaler.fit(data)

StandardScaler()

In [28]:
print("Mean:", scaler.mean_)
print("Variance:", scaler.var_)

Mean: [59.6 72.3 75.3 69.7 64.7 72.7 69.7 60.5]
Variance: [340.84 384.21 176.41 188.01 656.01 192.61 188.01 578.05]

In [30]:
scaled_data = scaler.transform(data)
scaled_data

array([[-0.24916243, -1.39276651, -1.45310069,  1.26169862, -1.70618534,
        -1.49152635,  1.40755973,  0.18716723],
       [ 0.83415247,  1.20910499,  0.20328352, -0.41570417,  0.98779152,
        -0.84303663, -0.85328751, -2.43317398],
       [-1.87413478, -0.93361271,  1.03147562,  0.4594625 ,  1.18300723,
         1.03037811, -0.99914862,  0.56150169],
       [ 0.99664971,  1.20910499,  0.80560505, -0.48863473, -0.41776163,
         1.17448693,  0.38653195, -0.64468712],
       [-0.08666519,  1.20910499,  0.20328352, -1.72845418,  1.22205037,
         0.30983398,  0.9699764 , -0.31194538],
       [-0.79081988,  0.7499512 , -1.75426145,  1.40755973, -0.37871849,
         1.17448693,  1.26169862, -0.3535381 ],
       [-0.24916243, -0.42344183, -1.07664973, -0.85328751,  0.40214437,
        -1.05919987, -0.41570417,  0.02079636],
       [-0.30332817,  0.18876323,  0.88089524, -0.99914862, -1.55001277,
        -1.2033087 ,  0.4594625 ,  1.10220702],
       [-0.24916243, -0.47445892,  1.03147562,  0.38653195,  0.5192738 ,
         0.16572515, -0.48863473,  1.18539245],
       [ 1.97163312, -1.34174942,  0.12799333,  0.9699764 , -0.26158906,
         0.74216045, -1.72845418,  0.68627984]])

In [32]:
scaled_data = scaler.transform(data)

scaled_df = pd.DataFrame(scaled_data, columns=subjects)

scaled_df

,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
0,-0.249162,-1.392767,-1.453101,1.261699,-1.706185,-1.491526,1.407560,0.187167
1,0.834152,1.209105,0.203284,-0.415704,0.987792,-0.843037,-0.853288,-2.433174
2,-1.874135,-0.933613,1.031476,0.459463,1.183007,1.030378,-0.999149,0.561502
3,0.996650,1.209105,0.805605,-0.488635,-0.417762,1.174487,0.386532,-0.644687
4,-0.086665,1.209105,0.203284,-1.728454,1.222050,0.309834,0.969976,-0.311945
5,-0.790820,0.749951,-1.754261,1.407560,-0.378718,1.174487,1.261699,-0.353538
6,-0.249162,-0.423442,-1.076650,-0.853288,0.402144,-1.059200,-0.415704,0.020796
7,-0.303328,0.188763,0.880895,-0.999149,-1.550013,-1.203309,0.459463,1.102207
8,-0.249162,-0.474459,1.031476,0.386532,0.519274,0.165725,-0.488635,1.185392
9,1.971633,-1.341749,0.127993,0.969976,-0.261589,0.742160,-1.728454,0.686280

# iris dataset

In [34]:
!pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.3-py3-none-any.whl.metadata (40 kB)
Collecting certifi>=2026.10.19 (from kagglehub)
  Downloading certifi-2026.10.19-py3-none-any.whl.metadata (2.5 kB)
Collecting kagglesdk<1.0,>=0.1.38 (from kagglehub)
  Downloading kagglesdk-0.1.38-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (26.2)
Requirement already satisfied: pyyaml in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (2.34.2)
Collecting tqdm (from kagglehub)
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
Collecting protobuf (from kagglesdk<1.0,>=0.1.38->kagglehub)
  Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (2.7.0)
Requirement already satisfied: colorama in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.3-py3-none-any.whl (73 kB)
Downloading kagglesdk-0.1.38-py3-none-any.whl (290 kB)
Downloading certifi-2026.10.19-py3-none-any.whl (136 kB)
Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl (456 kB)
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
Installing collected packages: tqdm, protobuf, certifi, kagglesdk, kagglehub

   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   -------- ------------------------------- 1/5 [protobuf]
   -------- ------------------------------- 1/5 [protobuf]
   -------- ------------------------------- 1/5 [protobuf]
   -------- ------------------------------- 1/5 [protobuf]
   -------- ------------------------------- 1/5 [protobuf]
   -------- ------------------------------- 1/5 [protobuf]
  Attempting uninstall: certifi
   -------- ------------------------------- 1/5 [protobuf]
    Found existing installation: certifi 2026.6.17
   -------- ------------------------------- 1/5 [protobuf]
    Uninstalling certifi-2026.6.17:
   -------- ------------------------------- 1/5 [protobuf]
      Successfully uninstalled certifi-2026.6.17
   -------- ------------------------------- 1/5 [protobuf]
   ---------------- ----------------------- 2/5 [certifi]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   -------------------------------- ------- 4/5 [kagglehub]
   -------------------------------- ------- 4/5 [kagglehub]
   -------------------------------- ------- 4/5 [kagglehub]
   ---------------------------------------- 5/5 [kagglehub]

Successfully installed certifi-2026.10.19 kagglehub-1.0.3 kagglesdk-0.1.38 protobuf-7.36.2 tqdm-4.70.1

  WARNING: The script tqdm.exe is installed in 'C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [35]:
import kagglehub
path = kagglehub.dataset_download("uciml/iris")

print("Path to dataset files:", path)

Downloading to C:\Users\ASUS\.cache\kagglehub\datasets\uciml\iris\2.archive...

100%|██████████| 3.60k/3.60k [00:00<00:00, 968kB/s]

Extracting files...
Path to dataset files: C:\Users\ASUS\.cache\kagglehub\datasets\uciml\iris\versions\2

In [36]:
import os

print(os.listdir(path))

['database.sqlite', 'Iris.csv']

In [38]:
import pandas as pd
import os

df = pd.read_csv(os.path.join(path, "Iris.csv"))

df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

### 1)probability using zscore
probability that Sepal Length is less than 5 cm

In [39]:
from scipy.stats import norm

mean = df['SepalLengthCm'].mean()
std = df['SepalLengthCm'].std()

x = 5

z = (x - mean) / std
print("Z-score:", z)

probability = norm.cdf(z)
print("Probability:", probability)

Z-score: -1.0184371813308597
Probability: 0.15423511999789297

In [40]:
#to find the probability of Sepal Length being greater than 5 cm:
probability = 1 - norm.cdf(z)
print("Probability:", probability)

Probability: 0.845764880002107

## 2) OUTLIER DETECTION

In [41]:
import numpy as np
from scipy.stats import zscore

z_scores = zscore(df['PetalLengthCm'])

threshold = 3

outliers = df[np.abs(z_scores) > threshold]

print("Outliers:")
print(outliers[['Id', 'PetalLengthCm', 'Species']])

Outliers:
Empty DataFrame
Columns: [Id, PetalLengthCm, Species]
Index: []

#### 3) scaling

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      -0.900681      1.032057      -1.341272     -1.312977
1      -1.143017     -0.124958      -1.341272     -1.312977
2      -1.385353      0.337848      -1.398138     -1.312977
3      -1.506521      0.106445      -1.284407     -1.312977
4      -1.021849      1.263460      -1.341272     -1.312977

#### 3) scaling

In [43]:
from sklearn.preprocessing import StandardScaler

subjects = [
    'SepalLengthCm',
    'SepalWidthCm',
    'PetalLengthCm',
    'PetalWidthCm'
]

data = df[subjects]

In [44]:
scaler = StandardScaler()

scaler.fit(data)

StandardScaler()

In [45]:
print("Mean:", scaler.mean_)
print("Variance:", scaler.var_)

Mean: [5.84333333 3.054      3.75866667 1.19866667]
Variance: [0.68112222 0.18675067 3.09242489 0.57853156]

In [46]:
scaled_data = scaler.transform(data)

print(scaled_data)

[[-9.00681170e-01  1.03205722e+00 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00 -1.24957601e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.38535265e+00  3.37848329e-01 -1.39813811e+00 -1.31297673e+00]
 [-1.50652052e+00  1.06445364e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.02184904e+00  1.26346019e+00 -1.34127240e+00 -1.31297673e+00]
 [-5.37177559e-01  1.95766909e+00 -1.17067529e+00 -1.05003079e+00]
 [-1.50652052e+00  8.00654259e-01 -1.34127240e+00 -1.18150376e+00]
 [-1.02184904e+00  8.00654259e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.74885626e+00 -3.56360566e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00  1.06445364e-01 -1.28440670e+00 -1.44444970e+00]
 [-5.37177559e-01  1.49486315e+00 -1.28440670e+00 -1.31297673e+00]
 [-1.26418478e+00  8.00654259e-01 -1.22754100e+00 -1.31297673e+00]
 [-1.26418478e+00 -1.24957601e-01 -1.34127240e+00 -1.44444970e+00]
 [-1.87002413e+00 -1.24957601e-01 -1.51186952e+00 -1.44444970e+00]
 [-5.25060772e-02  2.18907205e+00 -1.45500381e+00 -1.31297673e+00]
 [-1.73673948e-01  3.11468391e+00 -1.28440670e+00 -1.05003079e+00]
 [-5.37177559e-01  1.95766909e+00 -1.39813811e+00 -1.05003079e+00]
 [-9.00681170e-01  1.03205722e+00 -1.34127240e+00 -1.18150376e+00]
 [-1.73673948e-01  1.72626612e+00 -1.17067529e+00 -1.18150376e+00]
 [-9.00681170e-01  1.72626612e+00 -1.28440670e+00 -1.18150376e+00]
 [-5.37177559e-01  8.00654259e-01 -1.17067529e+00 -1.31297673e+00]
 [-9.00681170e-01  1.49486315e+00 -1.28440670e+00 -1.05003079e+00]
 [-1.50652052e+00  1.26346019e+00 -1.56873522e+00 -1.31297673e+00]
 [-9.00681170e-01  5.69251294e-01 -1.17067529e+00 -9.18557817e-01]
 [-1.26418478e+00  8.00654259e-01 -1.05694388e+00 -1.31297673e+00]
 [-1.02184904e+00 -1.24957601e-01 -1.22754100e+00 -1.31297673e+00]
 [-1.02184904e+00  8.00654259e-01 -1.22754100e+00 -1.05003079e+00]
 [-7.79513300e-01  1.03205722e+00 -1.28440670e+00 -1.31297673e+00]
 [-7.79513300e-01  8.00654259e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.38535265e+00  3.37848329e-01 -1.22754100e+00 -1.31297673e+00]
 [-1.26418478e+00  1.06445364e-01 -1.22754100e+00 -1.31297673e+00]
 [-5.37177559e-01  8.00654259e-01 -1.28440670e+00 -1.05003079e+00]
 [-7.79513300e-01  2.42047502e+00 -1.28440670e+00 -1.44444970e+00]
 [-4.16009689e-01  2.65187798e+00 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00  1.06445364e-01 -1.28440670e+00 -1.44444970e+00]
 [-1.02184904e+00  3.37848329e-01 -1.45500381e+00 -1.31297673e+00]
 [-4.16009689e-01  1.03205722e+00 -1.39813811e+00 -1.31297673e+00]
 [-1.14301691e+00  1.06445364e-01 -1.28440670e+00 -1.44444970e+00]
 [-1.74885626e+00 -1.24957601e-01 -1.39813811e+00 -1.31297673e+00]
 [-9.00681170e-01  8.00654259e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.02184904e+00  1.03205722e+00 -1.39813811e+00 -1.18150376e+00]
 [-1.62768839e+00 -1.74477836e+00 -1.39813811e+00 -1.18150376e+00]
 [-1.74885626e+00  3.37848329e-01 -1.39813811e+00 -1.31297673e+00]
 [-1.02184904e+00  1.03205722e+00 -1.22754100e+00 -7.87084847e-01]
 [-9.00681170e-01  1.72626612e+00 -1.05694388e+00 -1.05003079e+00]
 [-1.26418478e+00 -1.24957601e-01 -1.34127240e+00 -1.18150376e+00]
 [-9.00681170e-01  1.72626612e+00 -1.22754100e+00 -1.31297673e+00]
 [-1.50652052e+00  3.37848329e-01 -1.34127240e+00 -1.31297673e+00]
 [-6.58345429e-01  1.49486315e+00 -1.28440670e+00 -1.31297673e+00]
 [-1.02184904e+00  5.69251294e-01 -1.34127240e+00 -1.31297673e+00]
 [ 1.40150837e+00  3.37848329e-01  5.35295827e-01  2.64698913e-01]
 [ 6.74501145e-01  3.37848329e-01  4.21564419e-01  3.96171883e-01]
 [ 1.28034050e+00  1.06445364e-01  6.49027235e-01  3.96171883e-01]
 [-4.16009689e-01 -1.74477836e+00  1.37235899e-01  1.33225943e-01]
 [ 7.95669016e-01 -5.87763531e-01  4.78430123e-01  3.96171883e-01]
 [-1.73673948e-01 -5.87763531e-01  4.21564419e-01  1.33225943e-01]
 [ 5.53333275e-01  5.69251294e-01  5.35295827e-01  5.27644853e-01]
 [-1.14301691e+00 -1.51337539e+00 -2.60824029e-01 -2.61192967e-01]
 [ 9.16836886e-01 -3.56360566e-01  4.78430123e-01  1.33225943e-01]
 [-7.79513300e-01 -8.19166497e-01  8.03701950e-02  2.64698913e-01]
 [-1.02184904e+00 -2.43898725e+00 -1.47092621e-01 -2.61192967e-01]
 [ 6.86617933e-02 -1.24957601e-01  2.50967307e-01  3.96171883e-01]
 [ 1.89829664e-01 -1.97618132e+00  1.37235899e-01 -2.61192967e-01]
 [ 3.10997534e-01 -3.56360566e-01  5.35295827e-01  2.64698913e-01]
 [-2.94841818e-01 -3.56360566e-01 -9.02269170e-02  1.33225943e-01]
 [ 1.03800476e+00  1.06445364e-01  3.64698715e-01  2.64698913e-01]
 [-2.94841818e-01 -1.24957601e-01  4.21564419e-01  3.96171883e-01]
 [-5.25060772e-02 -8.19166497e-01  1.94101603e-01 -2.61192967e-01]
 [ 4.32165405e-01 -1.97618132e+00  4.21564419e-01  3.96171883e-01]
 [-2.94841818e-01 -1.28197243e+00  8.03701950e-02 -1.29719997e-01]
 [ 6.86617933e-02  3.37848329e-01  5.92161531e-01  7.90590793e-01]
 [ 3.10997534e-01 -5.87763531e-01  1.37235899e-01  1.33225943e-01]
 [ 5.53333275e-01 -1.28197243e+00  6.49027235e-01  3.96171883e-01]
 [ 3.10997534e-01 -5.87763531e-01  5.35295827e-01  1.75297293e-03]
 [ 6.74501145e-01 -3.56360566e-01  3.07833011e-01  1.33225943e-01]
 [ 9.16836886e-01 -1.24957601e-01  3.64698715e-01  2.64698913e-01]
 [ 1.15917263e+00 -5.87763531e-01  5.92161531e-01  2.64698913e-01]
 [ 1.03800476e+00 -1.24957601e-01  7.05892939e-01  6.59117823e-01]
 [ 1.89829664e-01 -3.56360566e-01  4.21564419e-01  3.96171883e-01]
 [-1.73673948e-01 -1.05056946e+00 -1.47092621e-01 -2.61192967e-01]
 [-4.16009689e-01 -1.51337539e+00  2.35044910e-02 -1.29719997e-01]
 [-4.16009689e-01 -1.51337539e+00 -3.33612130e-02 -2.61192967e-01]
 [-5.25060772e-02 -8.19166497e-01  8.03701950e-02  1.75297293e-03]
 [ 1.89829664e-01 -8.19166497e-01  7.62758643e-01  5.27644853e-01]
 [-5.37177559e-01 -1.24957601e-01  4.21564419e-01  3.96171883e-01]
 [ 1.89829664e-01  8.00654259e-01  4.21564419e-01  5.27644853e-01]
 [ 1.03800476e+00  1.06445364e-01  5.35295827e-01  3.96171883e-01]
 [ 5.53333275e-01 -1.74477836e+00  3.64698715e-01  1.33225943e-01]
 [-2.94841818e-01 -1.24957601e-01  1.94101603e-01  1.33225943e-01]
 [-4.16009689e-01 -1.28197243e+00  1.37235899e-01  1.33225943e-01]
 [-4.16009689e-01 -1.05056946e+00  3.64698715e-01  1.75297293e-03]
 [ 3.10997534e-01 -1.24957601e-01  4.78430123e-01  2.64698913e-01]
 [-5.25060772e-02 -1.05056946e+00  1.37235899e-01  1.75297293e-03]
 [-1.02184904e+00 -1.74477836e+00 -2.60824029e-01 -2.61192967e-01]
 [-2.94841818e-01 -8.19166497e-01  2.50967307e-01  1.33225943e-01]
 [-1.73673948e-01 -1.24957601e-01  2.50967307e-01  1.75297293e-03]
 [-1.73673948e-01 -3.56360566e-01  2.50967307e-01  1.33225943e-01]
 [ 4.32165405e-01 -3.56360566e-01  3.07833011e-01  1.33225943e-01]
 [-9.00681170e-01 -1.28197243e+00 -4.31421141e-01 -1.29719997e-01]
 [-1.73673948e-01 -5.87763531e-01  1.94101603e-01  1.33225943e-01]
 [ 5.53333275e-01  5.69251294e-01  1.27454998e+00  1.71090158e+00]
 [-5.25060772e-02 -8.19166497e-01  7.62758643e-01  9.22063763e-01]
 [ 1.52267624e+00 -1.24957601e-01  1.21768427e+00  1.18500970e+00]
 [ 5.53333275e-01 -3.56360566e-01  1.04708716e+00  7.90590793e-01]
 [ 7.95669016e-01 -1.24957601e-01  1.16081857e+00  1.31648267e+00]
 [ 2.12851559e+00 -1.24957601e-01  1.61574420e+00  1.18500970e+00]
 [-1.14301691e+00 -1.28197243e+00  4.21564419e-01  6.59117823e-01]
 [ 1.76501198e+00 -3.56360566e-01  1.44514709e+00  7.90590793e-01]
 [ 1.03800476e+00 -1.28197243e+00  1.16081857e+00  7.90590793e-01]
 [ 1.64384411e+00  1.26346019e+00  1.33141568e+00  1.71090158e+00]
 [ 7.95669016e-01  3.37848329e-01  7.62758643e-01  1.05353673e+00]
 [ 6.74501145e-01 -8.19166497e-01  8.76490051e-01  9.22063763e-01]
 [ 1.15917263e+00 -1.24957601e-01  9.90221459e-01  1.18500970e+00]
 [-1.73673948e-01 -1.28197243e+00  7.05892939e-01  1.05353673e+00]
 [-5.25060772e-02 -5.87763531e-01  7.62758643e-01  1.57942861e+00]
 [ 6.74501145e-01  3.37848329e-01  8.76490051e-01  1.44795564e+00]
 [ 7.95669016e-01 -1.24957601e-01  9.90221459e-01  7.90590793e-01]
 [ 2.24968346e+00  1.72626612e+00  1.67260991e+00  1.31648267e+00]
 [ 2.24968346e+00 -1.05056946e+00  1.78634131e+00  1.44795564e+00]
 [ 1.89829664e-01 -1.97618132e+00  7.05892939e-01  3.96171883e-01]
 [ 1.28034050e+00  3.37848329e-01  1.10395287e+00  1.44795564e+00]
 [-2.94841818e-01 -5.87763531e-01  6.49027235e-01  1.05353673e+00]
 [ 2.24968346e+00 -5.87763531e-01  1.67260991e+00  1.05353673e+00]
 [ 5.53333275e-01 -8.19166497e-01  6.49027235e-01  7.90590793e-01]
 [ 1.03800476e+00  5.69251294e-01  1.10395287e+00  1.18500970e+00]
 [ 1.64384411e+00  3.37848329e-01  1.27454998e+00  7.90590793e-01]
 [ 4.32165405e-01 -5.87763531e-01  5.92161531e-01  7.90590793e-01]
 [ 3.10997534e-01 -1.24957601e-01  6.49027235e-01  7.90590793e-01]
 [ 6.74501145e-01 -5.87763531e-01  1.04708716e+00  1.18500970e+00]
 [ 1.64384411e+00 -1.24957601e-01  1.16081857e+00  5.27644853e-01]
 [ 1.88617985e+00 -5.87763531e-01  1.33141568e+00  9.22063763e-01]
 [ 2.49201920e+00  1.72626612e+00  1.50201279e+00  1.05353673e+00]
 [ 6.74501145e-01 -5.87763531e-01  1.04708716e+00  1.31648267e+00]
 [ 5.53333275e-01 -5.87763531e-01  7.62758643e-01  3.96171883e-01]
 [ 3.10997534e-01 -1.05056946e+00  1.04708716e+00  2.64698913e-01]
 [ 2.24968346e+00 -1.24957601e-01  1.33141568e+00  1.44795564e+00]
 [ 5.53333275e-01  8.00654259e-01  1.04708716e+00  1.57942861e+00]
 [ 6.74501145e-01  1.06445364e-01  9.90221459e-01  7.90590793e-01]
 [ 1.89829664e-01 -1.24957601e-01  5.92161531e-01  7.90590793e-01]
 [ 1.28034050e+00  1.06445364e-01  9.33355755e-01  1.18500970e+00]
 [ 1.03800476e+00  1.06445364e-01  1.04708716e+00  1.57942861e+00]
 [ 1.28034050e+00  1.06445364e-01  7.62758643e-01  1.44795564e+00]
 [-5.25060772e-02 -8.19166497e-01  7.62758643e-01  9.22063763e-01]
 [ 1.15917263e+00  3.37848329e-01  1.21768427e+00  1.44795564e+00]
 [ 1.03800476e+00  5.69251294e-01  1.10395287e+00  1.71090158e+00]
 [ 1.03800476e+00 -1.24957601e-01  8.19624347e-01  1.44795564e+00]
 [ 5.53333275e-01 -1.28197243e+00  7.05892939e-01  9.22063763e-01]
 [ 7.95669016e-01 -1.24957601e-01  8.19624347e-01  1.05353673e+00]
 [ 4.32165405e-01  8.00654259e-01  9.33355755e-01  1.44795564e+00]
 [ 6.86617933e-02 -1.24957601e-01  7.62758643e-01  7.90590793e-01]]

In [47]:
print("Mean:", scaled_df.mean())

Mean: SepalLengthCm   -4.736952e-16
SepalWidthCm    -6.631732e-16
PetalLengthCm    3.315866e-16
PetalWidthCm    -2.842171e-16
dtype: float64